import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        foreground: "var(--foreground)",
        background: "var(--background)",
        "muted-foreground": "var(--muted-foreground)",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#ffd8fd",
        "on-background": "#e5e1e4",
        "secondary-fixed": "#ffd6fd",
        error: "#ffb4ab",
        "surface-tint": "#d0bcff",
        "on-primary-fixed-variant": "#5516be",
        "on-surface": "#e5e1e4",
        "tertiary-container": "#909191",
        primary: "#d0bcff",
        "on-secondary-fixed": "#36003e",
        "error-container": "#93000a",
        "inverse-primary": "#6d3bd7",
        "on-primary-container": "#340080",
        "surface-container-low": "#1c1b1d",
        surface: "#131315",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-fixed": "#23005c",
        "secondary-container": "#ae05c6",
        "surface-variant": "#353437",
        "on-primary": "#3c0091",
        "on-secondary": "#580065",
        "outline-variant": "#494454",
        tertiary: "#c6c6c7",
        "on-secondary-fixed-variant": "#7c008e",
        "on-tertiary": "#2f3131",
        "inverse-on-surface": "#313032",
        "surface-container": "#201f22",
        "primary-container": "#a078ff",
        "surface-dim": "#131315",
        "surface-container-high": "#2a2a2c",
        "on-tertiary-container": "#282a2a",
        "inverse-surface": "#e5e1e4",
        "surface-container-lowest": "#0e0e10",
        "on-surface-variant": "#cbc3d7",
        "primary-fixed-dim": "#d0bcff",
        "on-error": "#690005",
        "tertiary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#fbabff",
        secondary: "#fbabff",
        "surface-bright": "#39393b",
        "surface-container-highest": "#353437",
        "primary-fixed": "#e9ddff",
        outline: "#958ea0",
        "on-tertiary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#c6c6c7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-xl": "64px",
        "container-max": "1200px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        "headline-md": ["Geist"],
        "display-lg-mobile": ["Geist"],
        "body-lg": ["Inter"],
        "mono-code": ["Geist"],
        "body-md": ["Inter"],
        "label-sm": ["Geist"],
        "display-lg": ["Geist"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "mono-code": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      animation: {
        "aurora-bg": "aurora-smooth-bg 60s linear infinite",
      },
      keyframes: {
        "aurora-smooth-bg": {
          from: { backgroundPosition: "50% 50%, 50% 50%" },
          to: { backgroundPosition: "350% 50%, 350% 50%" },
        },
      },
    },
  },
  plugins: [],
};
export default config;